import instructor
from instructor import Mode
from instructor.processing.multimodal import Image, Audio, PDF
from pydantic import BaseModel, Field
from typing import Optional, Type, Generator, AsyncGenerator, get_args, get_origin, Dict, List, Callable, Union, Any
import logging
from atomic_agents.context.chat_history import ChatHistory
from atomic_agents.context.base_chat_history import BaseChatHistory
from atomic_agents.context.system_prompt_generator import (
    BaseDynamicContextProvider,
    SystemPromptGenerator,
    BaseSystemPromptGenerator,
)
from atomic_agents.base.base_io_schema import BaseIOSchema
from atomic_agents.utils.token_counter import get_token_counter, TokenCountResult
import json

from instructor.dsl.partial import PartialBase
from jiter import from_json

# Instructor modes whose prepared request carries the output schema as a
# tool/function definition instead of text inside the messages. Token accounting
# must agree with the actual request, so these modes are counted with a tools
# definition while all other modes append the schema to the system message.
# Keep aligned with Instructor's per-mode request preparation; the parametrized
# test in tests/agents/test_agent_mode_consistency.py prepares a request per
# mode and asserts this set matches what is actually sent.
# Mode.COHERE_TOOLS is deliberately absent: despite its name, its prepared
# request embeds the schema in an instruction message and sends no tool.
_TOOL_MODES = frozenset(
    {
        Mode.FUNCTIONS,
        Mode.PARALLEL_TOOLS,
        Mode.TOOLS,
        Mode.TOOLS_STRICT,
        Mode.RESPONSES_TOOLS,
        Mode.RESPONSES_TOOLS_WITH_INBUILT_TOOLS,
        Mode.ANTHROPIC_TOOLS,
        Mode.ANTHROPIC_REASONING_TOOLS,
        Mode.ANTHROPIC_PARALLEL_TOOLS,
        Mode.MISTRAL_TOOLS,
        Mode.VERTEXAI_TOOLS,
        Mode.VERTEXAI_PARALLEL_TOOLS,
        Mode.GEMINI_TOOLS,
        Mode.GENAI_TOOLS,
        Mode.XAI_TOOLS,
        Mode.CEREBRAS_TOOLS,
        Mode.FIREWORKS_TOOLS,
        Mode.WRITER_TOOLS,
        Mode.BEDROCK_TOOLS,
    }
)

# Instructor multimodal objects that can be lowered to a chat-format content part.
_InstructorMedia = Union[Image, Audio, PDF]


def model_from_chunks_patched(cls, json_chunks, **kwargs):
    potential_object = ""
    partial_model = cls.get_partial_model()
    for chunk in json_chunks:
        potential_object += chunk
        obj = from_json((potential_object or "{}").encode(), partial_mode="trailing-strings")
        obj = partial_model.model_validate(obj, strict=None, **kwargs)
        yield obj


async def model_from_chunks_async_patched(cls, json_chunks, **kwargs):
    potential_object = ""
    partial_model = cls.get_partial_model()
    async for chunk in json_chunks:
        potential_object += chunk
        obj = from_json((potential_object or "{}").encode(), partial_mode="trailing-strings")
        obj = partial_model.model_validate(obj, strict=None, **kwargs)
        yield obj


PartialBase.model_from_chunks = classmethod(model_from_chunks_patched)
PartialBase.model_from_chunks_async = classmethod(model_from_chunks_async_patched)


class BasicChatInputSchema(BaseIOSchema):
    """This schema represents the input from the user to the AI agent."""

    chat_message: str = Field(
        ...,
        description="The chat message sent by the user to the assistant.",
    )


class BasicChatOutputSchema(BaseIOSchema):
    """This schema represents the response generated by the chat agent."""

    chat_message: str = Field(
        ...,
        description=(
            "The chat message exchanged between the user and the chat agent. "
            "This contains the markdown-enabled response generated by the chat agent."
        ),
    )


class AgentConfig(BaseModel):
    client: instructor.core.client.Instructor = Field(..., description="Client for interacting with the language model.")
    model: str = Field(default="gpt-5-mini", description="The model to use for generating responses.")
    history: Optional[BaseChatHistory] = Field(default=None, description="History component for storing chat history.")
    system_prompt_generator: Optional[BaseSystemPromptGenerator] = Field(
        default=None,
        description=(
            "Component for generating system prompts. "
            "Defaults to SystemPromptGenerator if no subclass of BaseSystemPromptGenerator is passed."
        ),
    )
    system_role: Optional[str] = Field(
        default="system", description="The role of the system in the conversation. None means no system prompt."
    )
    assistant_role: str = Field(
        default="assistant",
        description="The role of the assistant in the conversation. Use 'model' for Gemini, 'assistant' for OpenAI/Anthropic.",
    )
    tool_result_role: Optional[str] = Field(
        default=None,
        description=(
            "The role to use for mid-conversation tool results and context injections. "
            "Defaults to 'user' when assistant_role is 'model' (Gemini), otherwise 'system'. "
            "Set explicitly to override auto-detection."
        ),
    )
    model_config = {"arbitrary_types_allowed": True}
    mode: Optional[Mode] = Field(
        default=None,
        description=(
            "The Instructor mode used for structured outputs (TOOLS, JSON, etc.). "
            "Drives token accounting only: modes that transmit the schema as a tool "
            "definition count it as a tool, others append it to the system message. "
            "When None, the client's mode is used; an explicit mode must agree with "
            "the client's mode on how the schema is transmitted, or a warning is logged."
        ),
    )
    model_api_parameters: Optional[dict] = Field(None, description="Additional parameters passed to the API provider.")
    max_context_tokens: Optional[int] = Field(
        None,
        description=(
            "Maximum tokens for the full context (system prompt + history + tools). "
            "When exceeded, oldest conversation turns are automatically trimmed to stay within limit. "
            "Uses LiteLLM's provider-agnostic token counter — works with any supported model."
        ),
    )


class AtomicAgent[InputSchema: BaseIOSchema, OutputSchema: BaseIOSchema]:
    """
    Base class for chat agents with full Instructor hook system integration.

    This class provides the core functionality for handling chat interactions, including managing history,
    generating system prompts, and obtaining responses from a language model. It includes comprehensive
    hook system support for monitoring and error handling.

    Type Parameters:
        InputSchema: Schema for the user input, must be a subclass of BaseIOSchema.
        OutputSchema: Schema for the agent's output, must be a subclass of BaseIOSchema.

    Attributes:
        client: Client for interacting with the language model.
        model (str): The model to use for generating responses.
        history (BaseChatHistory): History component for storing chat history.
        system_prompt_generator (BaseSystemPromptGenerator): Component for generating system prompts.
        system_role (Optional[str]): The role of the system in the conversation. None means no system prompt.
        assistant_role (str): The role of the assistant in the conversation. Use 'model' for Gemini, 'assistant' for OpenAI/Anthropic.
        initial_history (ChatHistory): Initial state of the history.
        current_user_input (Optional[InputSchema]): The current user input being processed.
        model_api_parameters (dict): Additional parameters passed to the API provider.
            - Use this for parameters like 'temperature', 'max_tokens', etc.
        max_context_tokens (Optional[int]): Maximum tokens for the full context. When exceeded,
            oldest conversation turns are automatically trimmed. Uses LiteLLM's token counter.

    Hook System:
        The AtomicAgent integrates with Instructor's hook system to provide comprehensive monitoring
        and error handling capabilities. Supported events include:

        - 'parse:error': Triggered when Pydantic validation fails
        - 'completion:kwargs': Triggered before completion request
        - 'completion:response': Triggered after completion response
        - 'completion:error': Triggered on completion errors
        - 'completion:last_attempt': Triggered on final retry attempt

    Hook Methods:
        - register_hook(event, handler): Register a hook handler for an event
        - unregister_hook(event, handler): Remove a hook handler
        - clear_hooks(event=None): Clear hooks for specific event or all events
        - enable_hooks()/disable_hooks(): Control hook processing
        - hooks_enabled: Property to check if hooks are enabled

    Example:
        ```python
        # Basic usage
        agent = AtomicAgent[InputSchema, OutputSchema](config)

        # Register parse error hook for intelligent retry handling
        def handle_parse_error(error):
            print(f"Validation failed: {error}")
            # Implement custom retry logic, logging, etc.

        agent.register_hook("parse:error", handle_parse_error)

        # Now parse:error hooks will fire on validation failures
        response = agent.run(user_input)
        ```
    """

    @classmethod
    def __init_subclass__(cls, **kwargs):
        """
        Hook called when a class is subclassed.

        Captures generic type parameters during class creation and stores them as class attributes
        to work around the unreliable __orig_class__ attribute in modern Python generic syntax.
        """
        super().__init_subclass__(**kwargs)
        if hasattr(cls, "__orig_bases__"):
            for base in cls.__orig_bases__:
                if get_origin(base) is AtomicAgent:
                    args = get_args(base)
                    if len(args) == 2:
                        cls._input_schema_cls = args[0]
                        cls._output_schema_cls = args[1]
                        break

    def __init__(self, config: AgentConfig):
        """
        Initializes the AtomicAgent.

        Args:
            config (AgentConfig): Configuration for the chat agent.
        """
        self.client = config.client
        self.model = config.model
        self.history = config.history if config.history is not None else ChatHistory()
        self.system_prompt_generator = config.system_prompt_generator or SystemPromptGenerator()
        self.system_role = config.system_role
        self.assistant_role = config.assistant_role
        self.tool_result_role = (
            config.tool_result_role
            if config.tool_result_role is not None
            else self._default_tool_result_role(config.assistant_role)
        )
        self.initial_history = self.history.copy()
        self.current_user_input = None
        self.mode = self._resolve_mode(config)
        self.model_api_parameters = config.model_api_parameters or {}
        self.max_context_tokens = config.max_context_tokens

        # Hook management attributes
        self._hook_handlers: Dict[str, List[Callable]] = {}
        self._hooks_enabled: bool = True

    @staticmethod
    def _default_tool_result_role(assistant_role: str) -> str:
        """
        Picks the role for tool results when AgentConfig does not override it.

        Gemini drops mid-conversation "system" messages, so Gemini backends
        (identified by assistant_role="model") receive tool results as user
        messages; every other backend uses "system".
        """
        return "user" if assistant_role == "model" else "system"

    def reset_history(self):
        """
        Resets the history to its initial state.
        """
        self.history = self.initial_history.copy()

    @staticmethod
    def _client_mode(client: instructor.Instructor) -> Optional[Mode]:
        """
        The mode of an Instructor client, when it exposes one.

        `AgentConfig` only accepts Instructor clients, but a client double or a
        custom client can still lack a comparable `mode` attribute; None is
        returned for them.
        """
        mode = getattr(client, "mode", None)
        return mode if isinstance(mode, Mode) else None

    @staticmethod
    def _modes_disagree(config_mode: Mode, client_mode: Optional[Mode]) -> bool:
        """
        Whether the two modes transmit the output schema differently.

        Only the transmission matters for token accounting: two modes that both
        send the schema as a tool definition are accounted for identically even
        when they target different providers.
        """
        if client_mode is None:
            return False
        return (config_mode in _TOOL_MODES) != (client_mode in _TOOL_MODES)

    @staticmethod
    def _warn_mode_mismatch(config_mode: Mode, client_mode: Mode) -> None:
        """Warns that token accounting will silently disagree with the API calls."""
        logging.getLogger(__name__).warning(
            "AgentConfig.mode (%s) and the Instructor client's mode (%s) disagree on how the "
            "output schema is transmitted, so token accounting will silently disagree with "
            "the actual API calls. Create the Instructor client with %s as well, or omit "
            "AgentConfig.mode to follow the client automatically.",
            config_mode.name,
            client_mode.name,
            config_mode.name,
        )

    @staticmethod
    def _resolve_mode(config: AgentConfig) -> Mode:
        """
        Resolves the effective Instructor mode used for token accounting.

        The API call format is decided by the mode the Instructor client was created
        with, so `AgentConfig.mode` follows the client by default. An explicitly
        configured mode that disagrees with the client on how the schema is
        transmitted warns, because token accounting then silently disagrees with
        the actual API calls.

        Args:
            config (AgentConfig): Configuration for the chat agent.

        Returns:
            Mode: The mode to use for token accounting.
        """
        client_mode = AtomicAgent._client_mode(config.client)

        if config.mode is None:
            return client_mode if client_mode is not None else Mode.TOOLS

        if AtomicAgent._modes_disagree(config.mode, client_mode):
            AtomicAgent._warn_mode_mismatch(config.mode, client_mode)
        return config.mode

    def add_tool_result(self, content: BaseIOSchema) -> None:
        """
        Adds a tool result or context injection to the chat history using the
        backend-appropriate role.

        This method should be used instead of ``history.add_message("system", ...)``
        when injecting tool execution results, resource contents, or other mid-conversation
        context into the agent's history. It automatically uses the correct role for the
        configured backend (e.g. ``"user"`` for Gemini, ``"system"`` for OpenAI/Anthropic).

        Args:
            content (BaseIOSchema): The tool result or context to inject.
        """
        self.history.add_message(self.tool_result_role, content)

    @property
    def input_schema(self) -> Type[BaseIOSchema]:
        """
        Returns the input schema for the agent.

        Uses a three-level fallback mechanism:
        1. Class attributes from __init_subclass__ (handles subclassing)
        2. Instance __orig_class__ (handles direct instantiation)
        3. Default schema (handles untyped usage)
        """
        # Inheritance pattern: MyAgent(AtomicAgent[Schema1, Schema2])
        if hasattr(self.__class__, "_input_schema_cls"):
            return self.__class__._input_schema_cls

        # Dynamic instantiation: AtomicAgent[Schema1, Schema2]()
        if hasattr(self, "__orig_class__"):
            TI, _ = get_args(self.__orig_class__)
            return TI

        # No type info available
        return BasicChatInputSchema

    @property
    def output_schema(self) -> Type[BaseIOSchema]:
        """
        Returns the output schema for the agent.

        Uses a three-level fallback mechanism:
        1. Class attributes from __init_subclass__ (handles subclassing)
        2. Instance __orig_class__ (handles direct instantiation)
        3. Default schema (handles untyped usage)
        """
        # Inheritance pattern: MyAgent(AtomicAgent[Schema1, Schema2])
        if hasattr(self.__class__, "_output_schema_cls"):
            return self.__class__._output_schema_cls

        # Dynamic instantiation: AtomicAgent[Schema1, Schema2]()
        if hasattr(self, "__orig_class__"):
            _, TO = get_args(self.__orig_class__)
            return TO

        # No type info available
        return BasicChatOutputSchema

    def _build_system_messages(self) -> List[Dict]:
        """
        Builds the system message(s) based on the configured system role.

        Returns:
            List[Dict]: A list containing the system message, or an empty list if system_role is None.
        """
        if self.system_role is None:
            return []
        return [
            {
                "role": self.system_role,
                "content": self.system_prompt_generator.generate_prompt(),
            }
        ]

    def _trim_context(self) -> None:
        """
        Trim oldest conversation turns to stay within max_context_tokens limit.

        Called before building the messages list. Uses the full context token count
        (system prompt + history + tools) via get_context_token_count().
        Removes oldest turns one at a time until the context fits within the limit,
        preserving the current turn so the request never loses its latest input.

        Turn-preserving: always removes complete turns, never individual messages.

        Raises:
            ValueError: If a single turn itself exceeds max_context_tokens.
        """
        if self.max_context_tokens is None:
            return

        result = self.get_context_token_count()
        total_tokens = result.total

        if total_tokens <= self.max_context_tokens:
            return

        logger = logging.getLogger(__name__)

        # Collect unique turn_ids in order (oldest first)
        turn_ids_ordered = []
        seen = set()
        for msg in self.history.history:
            if msg.turn_id and msg.turn_id not in seen:
                turn_ids_ordered.append(msg.turn_id)
                seen.add(msg.turn_id)

        # Remove oldest turns until within limit
        for turn_id in turn_ids_ordered:
            if total_tokens <= self.max_context_tokens:
                break
            if turn_id == self.history.current_turn_id:
                continue

            self.history.delete_turn_id(turn_id)
            new_result = self.get_context_token_count()
            removed = total_tokens - new_result.total
            total_tokens = new_result.total
            logger.warning(
                "Context exceeded max_context_tokens (%d). " "Trimmed turn '%s' (%d tokens). New total: %d.",
                self.max_context_tokens,
                turn_id,
                removed,
                total_tokens,
            )

        if total_tokens > self.max_context_tokens:
            raise ValueError(
                f"max_context_tokens ({self.max_context_tokens}) is smaller than the "
                f"minimum required for a single turn ({total_tokens} tokens). "
                "Increase max_context_tokens or reduce system prompt size."
            )

    def _prepare_messages(self):
        self.messages = self._build_system_messages()
        history = self.history.get_history()
        # Remap "system" role messages in history when the backend doesn't support
        # mid-conversation system messages (e.g. Gemini). The initial system prompt
        # is built separately via _build_system_messages() and is unaffected.
        if self.tool_result_role != "system":
            logger = logging.getLogger(__name__)
            for msg in history:
                if msg["role"] == "system":
                    logger.debug(
                        "Remapping mid-conversation 'system' message to '%s' "
                        "(backend does not support mid-conversation system messages).",
                        self.tool_result_role,
                    )
                    msg["role"] = self.tool_result_role
        self.messages += history

    def _get_completion_kwargs(self) -> Dict[str, Any]:
        """
        Build kwargs for Instructor completion calls.

        Instructor defaults `strict=True`, which forces enum fields to receive enum
        instances instead of allowing Pydantic's normal coercion from strings. We
        default to `strict=None` here so the output schema's own Pydantic behavior
        applies unless callers explicitly override it via `model_api_parameters`.
        """
        completion_kwargs = dict(self.model_api_parameters)
        completion_kwargs.setdefault("strict", None)
        return completion_kwargs

    def _build_tools_definition(self) -> Optional[List[Dict[str, Any]]]:
        """
        Build the tools definition that Instructor sends for TOOLS mode.

        This uses Instructor's actual schema generation to create the exact
        tools parameter that would be sent to the LLM for TOOLS mode.
        For JSON modes, returns None as the schema is embedded in messages.

        Returns:
            Optional[List[Dict[str, Any]]]: Tools definition for TOOLS mode, or None for JSON modes.
        """
        from instructor.processing.schema import generate_openai_schema

        # Only return tools for modes that transmit the schema as a tool definition
        if self.mode in _TOOL_MODES:
            return [
                {
                    "type": "function",
                    "function": generate_openai_schema(self.output_schema),
                }
            ]
        return None

    def _build_schema_for_json_mode(self) -> str:
        """
        Build the schema context for JSON modes (appended to system message).

        This matches exactly how Instructor formats the schema for JSON/MD_JSON modes.

        Returns:
            str: JSON schema string formatted as Instructor does.
        """
        from textwrap import dedent

        schema = self.output_schema.model_json_schema()
        return dedent(
            f"""
        As a genius expert, your task is to understand the content and provide
        the parsed objects in json that match the following json_schema:

        {json.dumps(schema, indent=2, ensure_ascii=False)}

        Make sure to return an instance of the JSON, not the schema itself
        """
        ).strip()

    def _serialize_history_for_token_count(self) -> List[Dict[str, Any]]:
        """
        Serialize conversation history for token counting, handling multimodal content.

        This method converts instructor multimodal objects (Image, Audio, PDF) to the
        OpenAI format that LiteLLM's token counter expects. Text content is also
        converted to the proper multimodal text format when mixed with media. Content-part
        dicts (e.g. video) become text placeholders because LiteLLM cannot count them.

        Returns:
            List[Dict[str, Any]]: History messages in LiteLLM-compatible format.
        """
        history = self.history.get_history()
        serialized = []

        for message in history:
            content = message.get("content")

            if isinstance(content, list):
                # Multimodal content - convert to the chat format the counter accepts
                serialized.append(
                    {
                        "role": message["role"],
                        "content": [self._token_count_content_part(item) for item in content],
                    }
                )
            else:
                # Simple text content - keep as is
                serialized.append(message)

        return serialized

    @staticmethod
    def _token_count_content_part(item: Union[str, _InstructorMedia, Dict[str, Any]]) -> Dict[str, Any]:
        """
        Converts one history content part to the chat format the token counter accepts.

        Args:
            item: A text part, an instructor multimodal object, or a content-part dict.
                Anything else is counted as its string form.

        Returns:
            Dict[str, Any]: The content part in LiteLLM-compatible format.
        """
        if isinstance(item, str):
            # Text content - wrap in OpenAI text format
            return {"type": "text", "text": item}
        if isinstance(item, (Image, Audio, PDF)):
            return AtomicAgent._serialize_media_for_token_count(item)
        if isinstance(item, dict):
            # get_history() emits pre-lowered content-part dicts (e.g. video).
            # LiteLLM's token counter only accepts text and image_url parts,
            # so estimate them with a placeholder.
            return {"type": "text", "text": f"[{item.get('type', 'unknown')} content]"}
        # Unknown type - convert to string
        return {"type": "text", "text": str(item)}

    @staticmethod
    def _serialize_media_for_token_count(item: _InstructorMedia) -> Dict[str, Any]:
        """
        Serializes an instructor media object to the chat format the token counter accepts.

        LiteLLM's counter only accepts chat-format content parts, so media is normalized
        to that format regardless of the agent's mode (Responses-format parts such as
        input_image raise). Serialization failures degrade to a text placeholder so
        counting still works.
        """
        try:
            return item.to_openai(Mode.JSON)
        except Exception as e:
            # Log the error and use placeholder for token estimation
            media_type = type(item).__name__
            logging.getLogger(__name__).warning(
                f"Failed to serialize {media_type} for token counting: {e}. Using placeholder for estimation."
            )
            return {"type": "text", "text": f"[{media_type.lower()} content]"}

    def get_context_token_count(self) -> TokenCountResult:
        """
        Get the accurate token count for the current context.

        This method computes the token count by serializing the context exactly
        as Instructor does, including:
        - System prompt
        - Conversation history (with multimodal content serialized properly)
        - Tools/schema overhead (using Instructor's actual schema generation)

        For TOOLS mode: Uses the actual tools parameter that Instructor sends.
        For JSON modes: Appends the schema to the system message as Instructor does.

        Works with any model supported by LiteLLM including OpenAI, Anthropic,
        Google, and 100+ other providers.

        Returns:
            TokenCountResult: A named tuple containing:
                - total: Total tokens in the complete message request; when tools
                  are provided without messages, this is schema-only overhead and
                  excludes request framing
                - system_prompt: System message tokens, including request framing
                  when a system message is present
                - history: Incremental tokens added by conversation history,
                  including request framing when no system message is present
                - tools: Incremental tokens added by tool definitions (TOOLS mode only)
                - model: The model used for counting
                - max_tokens: Maximum context window (if known)
                - utilization: Percentage of context used (if max_tokens known)

            The breakdown is additive: ``system_prompt + history + tools == total``.
            When tools are provided without system or history messages, ``total``
            and ``tools`` report schema-only overhead and exclude request framing.

        Example:
            ```python
            agent = AtomicAgent[InputSchema, OutputSchema](config)

            # Get accurate token count at any time
            result = agent.get_context_token_count()
            print(f"Total: {result.total} tokens")
            print(f"System: {result.system_prompt} tokens")
            print(f"History: {result.history} tokens")
            print(f"Tools: {result.tools} tokens")
            if result.utilization:
                print(f"Context usage: {result.utilization:.1%}")
            ```

        Note:
            The 'token:counted' hook event is dispatched, allowing for
            monitoring and logging of token usage.
        """
        counter = get_token_counter()

        # Build system messages
        system_messages = self._build_system_messages()

        # Handle schema serialization based on mode
        tools = self._build_tools_definition()

        if tools is None:
            # JSON mode - append schema to system message like Instructor does
            schema_context = self._build_schema_for_json_mode()
            if system_messages:
                system_messages = [
                    {
                        "role": system_messages[0]["role"],
                        "content": system_messages[0]["content"] + "\n\n" + schema_context,
                    }
                ]
            else:
                system_messages = [{"role": "system", "content": schema_context}]

        result = counter.count_context(
            model=self.model,
            system_messages=system_messages,
            history_messages=self._serialize_history_for_token_count(),
            tools=tools,
        )

        # Dispatch hook for monitoring
        self._dispatch_hook("token:counted", result)

        return result

    def run(self, user_input: Optional[InputSchema] = None) -> OutputSchema:
        """
        Runs the chat agent with the given user input synchronously.

        Args:
            user_input (Optional[InputSchema]): The input from the user. If not provided, skips adding to history.

        Returns:
            OutputSchema: The response from the chat agent.
        """
        assert not isinstance(
            self.client, instructor.core.client.AsyncInstructor
        ), "The run method is not supported for async clients. Use run_async instead."

        if user_input:
            self.history.initialize_turn()
            self.current_user_input = user_input
            self.history.add_message("user", user_input)

        self._trim_context()
        self._prepare_messages()
        response = self.client.chat.completions.create(
            messages=self.messages,
            model=self.model,
            response_model=self.output_schema,
            **self._get_completion_kwargs(),
        )
        self.history.add_message(self.assistant_role, response)
        self._prepare_messages()

        return response

    def run_stream(self, user_input: Optional[InputSchema] = None) -> Generator[OutputSchema, None, OutputSchema]:
        """
        Runs the chat agent with the given user input, supporting streaming output.

        Args:
            user_input (Optional[InputSchema]): The input from the user. If not provided, skips adding to history.

        Yields:
            OutputSchema: Partial responses from the chat agent.

        Returns:
            OutputSchema: The final response from the chat agent.
        """
        assert not isinstance(
            self.client, instructor.core.client.AsyncInstructor
        ), "The run_stream method is not supported for async clients. Use run_async instead."

        if user_input:
            self.history.initialize_turn()
            self.current_user_input = user_input
            self.history.add_message("user", user_input)

        self._trim_context()
        self._prepare_messages()

        response_stream = self.client.chat.completions.create_partial(
            model=self.model,
            messages=self.messages,
            response_model=self.output_schema,
            **self._get_completion_kwargs(),
            stream=True,
        )

        last_response = None
        for partial_response in response_stream:
            last_response = partial_response
            yield partial_response

        if last_response:
            full_response_content = self.output_schema(**last_response.model_dump())
            self.history.add_message(self.assistant_role, full_response_content)
            self._prepare_messages()
            return full_response_content

    async def run_async(self, user_input: Optional[InputSchema] = None) -> OutputSchema:
        """
        Runs the chat agent asynchronously with the given user input.

        Args:
            user_input (Optional[InputSchema]): The input from the user. If not provided, skips adding to history.

        Returns:
            OutputSchema: The response from the chat agent.

        Raises:
            NotAsyncIterableError: If used as an async generator (in an async for loop).
                                   Use run_async_stream() method instead for streaming responses.
        """
        assert isinstance(self.client, instructor.core.client.AsyncInstructor), "The run_async method is for async clients."

        if user_input:
            self.history.initialize_turn()
            self.current_user_input = user_input
            self.history.add_message("user", user_input)

        self._trim_context()
        self._prepare_messages()

        response = await self.client.chat.completions.create(
            model=self.model, messages=self.messages, response_model=self.output_schema, **self._get_completion_kwargs()
        )

        self.history.add_message(self.assistant_role, response)
        self._prepare_messages()
        return response

    async def run_async_stream(self, user_input: Optional[InputSchema] = None) -> AsyncGenerator[OutputSchema, None]:
        """
        Runs the chat agent asynchronously with the given user input, supporting streaming output.

        Args:
            user_input (Optional[InputSchema]): The input from the user. If not provided, skips adding to history.

        Yields:
            OutputSchema: Partial responses from the chat agent.
        """
        assert isinstance(self.client, instructor.core.client.AsyncInstructor), "The run_async method is for async clients."
        if user_input:
            self.history.initialize_turn()
            self.current_user_input = user_input
            self.history.add_message("user", user_input)

        self._trim_context()
        self._prepare_messages()

        response_stream = self.client.chat.completions.create_partial(
            model=self.model,
            messages=self.messages,
            response_model=self.output_schema,
            **self._get_completion_kwargs(),
            stream=True,
        )

        last_response = None
        async for partial_response in response_stream:
            last_response = partial_response
            yield partial_response

        if last_response:
            full_response_content = self.output_schema(**last_response.model_dump())
            self.history.add_message(self.assistant_role, full_response_content)
            self._prepare_messages()

    def get_context_provider(self, provider_name: str) -> Type[BaseDynamicContextProvider]:
        """
        Retrieves a context provider by name.

        Args:
            provider_name (str): The name of the context provider.

        Returns:
            BaseDynamicContextProvider: The context provider if found.

        Raises:
            KeyError: If the context provider is not found.
        """
        if provider_name not in self.system_prompt_generator.context_providers:
            raise KeyError(f"Context provider '{provider_name}' not found.")
        return self.system_prompt_generator.context_providers[provider_name]

    def register_context_provider(self, provider_name: str, provider: BaseDynamicContextProvider):
        """
        Registers a new context provider.

        Args:
            provider_name (str): The name of the context provider.
            provider (BaseDynamicContextProvider): The context provider instance.
        """
        self.system_prompt_generator.context_providers[provider_name] = provider

    def unregister_context_provider(self, provider_name: str):
        """
        Unregisters an existing context provider.

        Args:
            provider_name (str): The name of the context provider to remove.
        """
        if provider_name in self.system_prompt_generator.context_providers:
            del self.system_prompt_generator.context_providers[provider_name]
        else:
            raise KeyError(f"Context provider '{provider_name}' not found.")

    # Hook Management Methods
    def register_hook(self, event: str, handler: Callable) -> None:
        """
        Registers a hook handler for a specific event.

        Args:
            event (str): The event name (e.g., 'parse:error', 'completion:kwargs', etc.)
            handler (Callable): The callback function to handle the event
        """
        if event not in self._hook_handlers:
            self._hook_handlers[event] = []
        self._hook_handlers[event].append(handler)

        # Register with instructor client if it supports hooks
        if hasattr(self.client, "on"):
            self.client.on(event, handler)

    def unregister_hook(self, event: str, handler: Callable) -> None:
        """
        Unregisters a hook handler for a specific event.

        Args:
            event (str): The event name
            handler (Callable): The callback function to remove
        """
        if event in self._hook_handlers and handler in self._hook_handlers[event]:
            self._hook_handlers[event].remove(handler)

            # Remove from instructor client if it supports hooks
            if hasattr(self.client, "off"):
                self.client.off(event, handler)

    def clear_hooks(self, event: Optional[str] = None) -> None:
        """
        Clears hook handlers for a specific event or all events.

        Args:
            event (Optional[str]): The event name to clear, or None to clear all
        """
        if event:
            if event in self._hook_handlers:
                # Clear from instructor client first
                if hasattr(self.client, "clear"):
                    self.client.clear(event)
                self._hook_handlers[event].clear()
        else:
            # Clear all hooks
            if hasattr(self.client, "clear"):
                self.client.clear()
            self._hook_handlers.clear()

    def _dispatch_hook(self, event: str, *args, **kwargs) -> None:
        """
        Internal method to dispatch hook events with error isolation.

        Args:
            event (str): The event name
            *args: Arguments to pass to handlers
            **kwargs: Keyword arguments to pass to handlers
        """
        if not self._hooks_enabled or event not in self._hook_handlers:
            return

        for handler in self._hook_handlers[event]:
            try:
                handler(*args, **kwargs)
            except Exception as e:
                # Log error but don't interrupt main flow
                logger = logging.getLogger(__name__)
                logger.warning(f"Hook handler for '{event}' raised exception: {e}")

    def enable_hooks(self) -> None:
        """Enable hook processing."""
        self._hooks_enabled = True

    def disable_hooks(self) -> None:
        """Disable hook processing."""
        self._hooks_enabled = False

    @property
    def hooks_enabled(self) -> bool:
        """Check if hooks are enabled."""
        return self._hooks_enabled


if __name__ == "__main__":
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    from rich.syntax import Syntax
    from rich import box
    from openai import OpenAI, AsyncOpenAI
    import instructor
    import asyncio
    from rich.live import Live

    def _create_schema_table(title: str, schema: Type[BaseModel]) -> Table:
        """Create a table displaying schema information.

        Args:
            title (str): Title of the table
            schema (Type[BaseModel]): Schema to display

        Returns:
            Table: Rich table containing schema information
        """
        schema_table = Table(title=title, box=box.ROUNDED)
        schema_table.add_column("Field", style="cyan")
        schema_table.add_column("Type", style="magenta")
        schema_table.add_column("Description", style="green")

        for field_name, field in schema.model_fields.items():
            schema_table.add_row(field_name, str(field.annotation), field.description or "")

        return schema_table

    def _create_config_table(agent: AtomicAgent) -> Table:
        """Create a table displaying agent configuration.

        Args:
            agent (AtomicAgent): Agent instance

        Returns:
            Table: Rich table containing configuration information
        """
        info_table = Table(title="Agent Configuration", box=box.ROUNDED)
        info_table.add_column("Property", style="cyan")
        info_table.add_column("Value", style="yellow")

        info_table.add_row("Model", agent.model)
        info_table.add_row("History", str(type(agent.history).__name__))
        info_table.add_row("System Prompt Generator", str(type(agent.system_prompt_generator).__name__))

        return info_table

    def display_agent_info(agent: AtomicAgent):
        """Display information about the agent's configuration and schemas."""
        console = Console()
        console.print(
            Panel.fit(
                "[bold blue]Agent Information[/bold blue]",
                border_style="blue",
                padding=(1, 1),
            )
        )

        # Display input schema
        input_schema_table = _create_schema_table("Input Schema", agent.input_schema)
        console.print(input_schema_table)

        # Display output schema
        output_schema_table = _create_schema_table("Output Schema", agent.output_schema)
        console.print(output_schema_table)

        # Display configuration
        info_table = _create_config_table(agent)
        console.print(info_table)

        # Display system prompt
        system_prompt = agent.system_prompt_generator.generate_prompt()
        console.print(
            Panel(
                Syntax(system_prompt, "markdown", theme="monokai", line_numbers=True),
                title="Sample System Prompt",
                border_style="green",
                expand=False,
            )
        )

    async def chat_loop(streaming: bool = False):
        """Interactive chat loop with the AI agent.

        Args:
            streaming (bool): Whether to use streaming mode for responses
        """
        if streaming:
            client = instructor.from_openai(AsyncOpenAI())
            config = AgentConfig(client=client, model="gpt-5-mini")
            agent = AtomicAgent[BasicChatInputSchema, BasicChatOutputSchema](config)
        else:
            client = instructor.from_openai(OpenAI())
            config = AgentConfig(client=client, model="gpt-5-mini")
            agent = AtomicAgent[BasicChatInputSchema, BasicChatOutputSchema](config)

        # Display agent information before starting the chat
        display_agent_info(agent)

        console = Console()
        console.print(
            Panel.fit(
                "[bold blue]Interactive Chat Mode[/bold blue]\n"
                f"[cyan]Streaming: {streaming}[/cyan]\n"
                "Type 'exit' to quit",
                border_style="blue",
                padding=(1, 1),
            )
        )

        while True:
            user_message = console.input("\n[bold green]You:[/bold green] ")

            if user_message.lower() == "exit":
                console.print("[yellow]Goodbye![/yellow]")
                break

            user_input = agent.input_schema(chat_message=user_message)

            console.print("[bold blue]Assistant:[/bold blue]")
            if streaming:
                with Live(console=console, refresh_per_second=4) as live:
                    # Use run_async_stream instead of run_async for streaming responses
                    async for partial_response in agent.run_async_stream(user_input):
                        response_json = partial_response.model_dump()
                        json_str = json.dumps(response_json, indent=2)
                        live.update(json_str)
            else:
                response = agent.run(user_input)
                response_json = response.model_dump()
                json_str = json.dumps(response_json, indent=2)
                console.print(json_str)

    console = Console()
    console.print("\n[bold]Starting chat loop...[/bold]")
    asyncio.run(chat_loop(streaming=True))
